### PR TITLE
bugfix : offset can not use without limit value

### PR DESCRIPTION
**Pull request by foronedream**
offset can not use without limit value
## Summary

offset can not use without limit value

## Solution Description

offset can not use without limit value

### CODE REVIEW

**Comment by IHEII** [comment]
Seems have not signed the license yet

**Comment by IHEII** [comment]
It's better to comment [here](https://github.com/oceanbase/obkv-table-client-go/blob/135b6c0b0bb8ee5d89124cfc28483d8f030a9d43/example/query/query.go#L48C23-L48C23 )

**Comment by foronedream** [comment]
> It's better to comment [here](https://github.com/oceanbase/obkv-table-client-go/blob/135b6c0b0bb8ee5d89124cfc28483d8f030a9d43/example/query/query.go#L48C23-L48C23)
down

**Comment by IHEII** [comment]
LGTM

**Pull request merged**
